services:
  api:
    container_name: petcare_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PORT=3500
    ports:
      - "3500:3500"
    depends_on:
      postgresdb:
        condition: service_healthy
    networks:
      - backend_net
  postgresdb:
    image: postgres:16-alpine
    container_name: petcare_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=petcare_user
      - POSTGRES_PASSWORD=petpassdb
      - POSTGRES_DB=petcare_db
    networks:
      - backend_net
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petcare_user -d petcare_db"]
      interval: 15s
      timeout: 5s
      retries: 5

networks:
  backend_net:
    driver: bridge

volumes:
  db_data:
